### ISSUE TITLE
Drupal-specific functions

### ISSUE THREAD

**Issue by colemanw** [DizzyMissLizzy/be.dizzymisslizzy.pdfletterevents#1]
I notice you are using at least one drupal-only function (drupal_static).
Those need to be removed before this can be approved for automatic distribution on civicrm.org.
Thanks!

**Comment by sgladstone** [comment]
I fixed the code to remove the Drupal function "drupal_static".  I am waiting on the PR to be merged. ( https://github.com/DizzyMissLizzy/be.dizzymisslizzy.pdfletterevents/pull/2 )
